language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: djA7IdKfpPxNnna4/KK0exT4TzijTT5UyDYq8Bvu2Cf7dPvsv8ZVbo3InFP+o030evydIhASyYnwfNsCXAB2OFPAW9rTkHsdDR41LhHTKyTk42YGWXHNbQK/zWr7BCHaLCoNHVawPPF/PghbDNqh564nHLsfWfhz2cY9PfcML4yMlKmsjfGAjIJJd2kKTeezLMHhH6xXKHRoPNcRtP7EI2I8IgZ6lfmQwrTk+dCDkJhxm/J6FG0bl9PhuR7ZLsEMkZVfQIC58mn6g6dGwnt8/SYVQiDtVhbXlXtzZQbnzkU91Uo9X9ld/HT6VPR3D3VnJXHjNGD1uo4wpFUfrIIr1lmcL9iSbSBC000C+4cUJHAMwaxN+qijplRvfXF16X72YFfgOUb6cmrHhpe1/NrTHf2AaIcX8fnji17Ls+BQq2Y+EluHh0vEniGoQAE7d5TK0W7nT3gtEJKlfO9XaIbHSyrIizmC/HCJ4lCauWWyBLOuG/PHMNeBOhHou7k2VosSDbUuVerz3mQ54tYM/PI+M4Rxa5s3KXkOaSEGpZRBgm0JNmRo62vGnPusj7pi9LRMBly3RNNJVraH99vYObNSgi/KXiPvmPLxwdMyuXvotYeMxAhCDLrxGsDl9s7A83gV6VwqpgeEISkeHhfD2F+rN/bO4GyNnvUpuyFQhWGfTLg=
  on:
    tags: true
    repo: leeeeon4/leeeeon4_test_package
    python: 3.8
