language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: bGMtGuwYdWR1Mzq7NeRBjkDI5UaRRgyH7J7HOsNSudtWRkcHdHVbGxhHxsbV7ZroiZtdNLejc3oRnHnT+9D+I/lyL0k5DQlJqQtUsIY4/e56cidoHClsuSVYBbR7iDqyh3Nw73FzncGw2WGLXo9Byo6jZEbZrmKHahaxCoSzD6QXL8itcYmHTshdvmmUYs18kT795um6wRmuLLPXtX0df47tZZQ9AIkugLwwDL6hjzx33I8ywlqbmC6bsknDJz4yNdzIlVDO64fJPzAph+X4GQ5ULUeNvVpu1MAl+vMQci3fLoPtbcZlog5V6HSI4SXnIzT5gYwAyDWh9My+lo6hmffjVqhvf642dvN16lweetdsK6WWcRW4bQDo8pfYahAjobYDrNFNQxc9gKzDHMT1tlAFotkV7m/O7gWPYbMR54i8Yb0OFzHmeAi3Gwc7A40vrYR8d62HeQRLQtULXcsvhIWeq/FwUNvOQbUBoRoeB2F2sumY1KsQK32bA72hJwrzELJ6WVp9+4JoYSS9htdNYagjZKJe2s3sjdHmCyxaJEeciYXvM0mbKr6FFN1UKo3+AAdkLtgEfdaPuGAFWnUgWDt2PZiHmStUqlGJMR3ly2DxLMTd488A+9LUNpKQUy7McOKLjBYdyqamgGIJu4iFl68OE5RKYQaKb34WPpzw42E=
  on:
    tags: true
    repo: leeeeon4/leeeeon4_test_package
    python: 3.9
